from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "books" / "01-llm-app-dev-for-mobile-engineers" / "book-manifest.json"
DEFAULT_OUTPUT = ROOT / "build" / "book.md"

INLINE_LINK_RE = re.compile(
    r"(!?\[[^\]\n]*]\()"
    r"(<[^>\n]*>|[^)\s]+)"
    r"((?:[ \t]+(?:\"[^\"\n]*\"|'[^'\n]*'|\([^)\n]*\)))?)"
    r"(\))"
)
REFERENCE_DEF_RE = re.compile(r"^(\s{0,3}\[([^\]\n]+)]\:\s*)(.+)$")
REFERENCE_USE_RE = re.compile(r"!?\[([^\]\n]+)]\[([^\]\n]*)]")
SCHEME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")


def build_book(output_path: Path, manifest_path: Path = MANIFEST_PATH) -> dict[str, int | str]:
    output_path = output_path.resolve()
    manifest_path = manifest_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    book_files = _load_book_files(manifest_path=manifest_path)

    sections: list[str] = [
        f"<!-- Generated by tools/build_book.py from {manifest_path.relative_to(ROOT)}. -->",
        "",
    ]
    source_count = 0
    for relative_path in book_files:
        source_path = ROOT / relative_path
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing source file: {relative_path}")
        source_count += 1
        text = source_path.read_text(encoding="utf-8")
        sections.append(f"<!-- source: {relative_path} -->")
        sections.append(_rewrite_relative_links(text, source_path, output_path, ROOT))
        sections.append("")

    content = "\n".join(sections).rstrip() + "\n"
    output_path.write_text(content, encoding="utf-8")
    return {
        "output": str(output_path),
        "source_count": source_count,
        "characters": len(content),
    }


def _load_book_files(manifest_path: Path = MANIFEST_PATH, root: Path = ROOT) -> list[str]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    source_order = manifest.get("source_order")
    if not isinstance(source_order, list) or not source_order:
        raise ValueError(f"Manifest must contain a non-empty source_order list: {manifest_path}")

    root = root.resolve()
    book_files: list[str] = []
    seen_paths: set[str] = set()
    for index, item in enumerate(source_order, start=1):
        if not isinstance(item, dict):
            raise ValueError(f"Manifest source_order item #{index} must be an object")
        relative_path = item.get("path")
        if not isinstance(relative_path, str) or not relative_path:
            raise ValueError(f"Manifest source_order item #{index} has an invalid path")
        if Path(relative_path).is_absolute():
            raise ValueError(f"Manifest path must be relative: {relative_path}")

        resolved = (root / relative_path).resolve()
        try:
            resolved.relative_to(root)
        except ValueError as exc:
            raise ValueError(f"Manifest path escapes repository: {relative_path}") from exc

        if relative_path in seen_paths:
            raise ValueError(f"Duplicate manifest path: {relative_path}")
        seen_paths.add(relative_path)
        book_files.append(relative_path)
    return book_files


def _rewrite_relative_links(
    text: str,
    source_path: Path,
    output_path: Path,
    root: Path = ROOT,
) -> str:
    root = root.resolve()
    reference_definitions = _collect_reference_definitions(text, source_path, output_path, root)
    lines: list[str] = []
    in_fence = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            lines.append(line)
            continue
        if in_fence:
            lines.append(line)
            continue
        line = _rewrite_reference_definition(line, source_path, output_path, root)
        _validate_reference_uses(line, source_path, reference_definitions)
        lines.append(
            INLINE_LINK_RE.sub(lambda match: _rewrite_inline_link(match, source_path, output_path, root), line)
        )
    return "\n".join(lines)


def _collect_reference_definitions(
    text: str,
    source_path: Path,
    output_path: Path,
    root: Path,
) -> set[str]:
    definitions: set[str] = set()
    in_fence = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = REFERENCE_DEF_RE.match(line)
        if not match:
            continue
        definitions.add(_normalize_reference_label(match.group(2)))
        target, _ = _parse_destination(match.group(3), source_path)
        _resolve_local_target(target, source_path, output_path, root)
    return definitions


def _rewrite_reference_definition(
    line: str,
    source_path: Path,
    output_path: Path,
    root: Path,
) -> str:
    match = REFERENCE_DEF_RE.match(line)
    if not match:
        return line
    target, suffix = _parse_destination(match.group(3), source_path)
    return f"{match.group(1)}{_rewrite_target(target, source_path, output_path, root)}{suffix}"


def _validate_reference_uses(line: str, source_path: Path, definitions: set[str]) -> None:
    if REFERENCE_DEF_RE.match(line):
        return
    for match in REFERENCE_USE_RE.finditer(line):
        label = match.group(2) or match.group(1)
        if _normalize_reference_label(label) not in definitions:
            raise ValueError(f"Undefined reference link in {_display_path(source_path)}: {match.group(0)}")


def _rewrite_inline_link(
    match: re.Match[str],
    source_path: Path,
    output_path: Path,
    root: Path,
) -> str:
    prefix, target, title, suffix = match.groups()
    return f"{prefix}{_rewrite_target(target, source_path, output_path, root)}{title}{suffix}"


def _rewrite_target(
    target: str,
    source_path: Path,
    output_path: Path,
    root: Path,
) -> str:
    resolved = _resolve_local_target(target, source_path, output_path, root)
    if resolved is None:
        return target
    path_part, fragment, was_angled = resolved
    relative = os.path.relpath(path_part, output_path.parent.resolve()).replace(os.sep, "/")
    if fragment:
        relative = f"{relative}#{fragment}"
    if was_angled or any(char.isspace() for char in relative):
        return f"<{relative}>"
    return relative


def _resolve_local_target(
    target: str,
    source_path: Path,
    output_path: Path,
    root: Path,
) -> tuple[Path, str, bool] | None:
    path_part, fragment, was_angled = _split_destination(target)
    if _is_external_or_anchor(path_part):
        return None
    if not path_part:
        return None
    if SCHEME_RE.match(path_part):
        raise ValueError(f"Unsupported local link scheme in {_display_path(source_path)}: {target}")
    if Path(path_part).is_absolute():
        raise ValueError(f"Absolute local link is not portable in {_display_path(source_path)}: {target}")

    source_target = (source_path.parent / path_part).resolve()
    if not source_target.exists():
        raise FileNotFoundError(f"Broken local link in {_display_path(source_path)}: {target}")
    try:
        source_target.relative_to(root)
    except ValueError as exc:
        raise ValueError(
            f"Local link escapes repository in {_display_path(source_path)}: {target}"
        ) from exc
    return source_target, fragment, was_angled


def _parse_destination(text: str, source_path: Path) -> tuple[str, str]:
    stripped = text.lstrip()
    leading = text[: len(text) - len(stripped)]
    if not stripped:
        raise ValueError(f"Missing reference link target in {_display_path(source_path)}")
    if stripped.startswith("<"):
        end = stripped.find(">")
        if end == -1:
            raise ValueError(f"Malformed angle-bracket link in {_display_path(source_path)}: {text}")
        return stripped[: end + 1], leading + stripped[end + 1 :]
    parts = stripped.split(maxsplit=1)
    suffix = leading + (f" {parts[1]}" if len(parts) > 1 else "")
    return parts[0], suffix


def _is_external_or_anchor(target: str) -> bool:
    return target.startswith(("http://", "https://", "#", "mailto:"))


def _split_destination(target: str) -> tuple[str, str, bool]:
    was_angled = target.startswith("<") and target.endswith(">")
    if was_angled:
        target = target[1:-1]
    if "#" not in target:
        return target, "", was_angled
    path_part, fragment = target.split("#", 1)
    return path_part, fragment, was_angled


def _normalize_reference_label(label: str) -> str:
    return " ".join(label.casefold().split())


def _display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a single Markdown manuscript from ordered source files.")
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    result = build_book(args.output, args.manifest)
    print(f"built {result['output']}")
    print(f"sources {result['source_count']}")
    print(f"characters {result['characters']}")


if __name__ == "__main__":
    main()
